### ISSUE TITLE
No Autocomplete in Swift projects in XCode 7

### ISSUE THREAD

**Issue by abbeyjackson** [kif-framework/KIF#837]
At work we use KIF extensively and there are many Swift projects where autocomplete no longer works. This is not a session based behaviour, you can clone a new copy of the repo and autocomplete in KIF is nonexistent. All projects starts off with KIF autocomplete working but after a bit it stops. We have theorized it has something to do with the size of the project but no one seems to know for certain. 

Is this a known issue? Is there a fix for it?

**Comment by mikelupo** [comment]
Hi Abbey,
Not that I can answer your question but it might be relevant to know which Xcode and which OS version.

**Comment by abbeyjackson** [comment]
I’m not sure that it is relevant since this is a company wide thing I am
seeing. People are working on all different OSX versions and all different
XCode versions but I assume we are all on Xcode 7 something if we are on a
Swift project.


Sincerely,

Abbey Jackson

604-600-1450
https://github.com/abbeyjackson
http://ca.linkedin.com/in/earthabbey

**Comment by skyem** [comment]
I would add that I'm only seeing this issue when KIF is used as a framework in cocoapods.

**Comment by abbeyjackson** [comment]
Oh, that’s a good catch. That is the only way we use it in our projects so
I can’t say if we would have the same problem otherwise.

**Comment by skyem** [comment]
One other thing to mention is that I've found that goes along with this issue that all of the KIF tests run as  runtime tests instead of being individually selectable. My temp fix for this aspect of it was to change my test classes to XCTestCase instead of KIFTestCase.

**Comment by phatmann** [comment]
If autocomplete stops working and tests are not being discovered, this means that Xcode's "index" is corrupt. The standard fix for this is to go to the Window/Projects view and delete the Derived Data folder. 

That said, the real question is why the index is being corrupted in the first place.

**Comment by abbeyjackson** [comment]
I don’t know if this is the problem in this case. Deleting XCode’s derived
data and cache folders have no effect.

**Comment by skyem** [comment]
I've found that adding a recursive $(SRCROOT) to the header search paths fixes the autocomplete and the finding of the tests, but it won't build due to a lot of redefinition errors.

**Comment by phatmann** [comment]
@skyem Great that you have figured out that this is a path issue! Are you willing to play around with this some more to find a header search path that works correctly?

**Comment by skyem** [comment]
Sure, I'd be glad to.

**Comment by skyem** [comment]
I've narrowed it down to this: "$(SRCROOT)/Pods/Headers" recursive. That is what's fixing the autocomplete and is enabling Xcode to find the tests again. I still get the failed build with all of the redefinition errors. If I direct it specifically to "$(SRCROOT)/Pods/Headers/Private/KIF", the problem returns.

**Comment by phatmann** [comment]
Good work. Can you figure out where the redefinition errors are coming from?

**Comment by skyem** [comment]
I haven't been able to find a solution for the redefinition errors. What I believe is happening is that adding the headers search path allows Xcode to make a proper index which causes the autocompletion to work and allows the tests to be found, but when it goes to build, the whole KIF library gets defined twice. One other thing I've found is that this only works if KIF is imported as #import <KIF/KIF.h> in the bridging header. @import KIF doesn't work.

**Comment by phatmann** [comment]
This is frustrating. Any chance you can provide a sample project? Then I can play around along with you to try and find some answers. Last I checked Xcode was a finite state machine...and we should be able to get to the bottom of this :-)

**Comment by abbeyjackson** [comment]
We have talked about it but we can not provide client code to a third party. We are trying to think of ways...

**Comment by skyem** [comment]
We've finally found a solution for this! We normally use a scheme that has Sharing turned on for use with Jenkins. Deleting the scheme, making a new one with defaults, resetting derived data, cleaning, and resetting the sim gets it going again. Now we're just making a second scheme with sharing turned on for Jenkins. It's so good to have autocomplete back and test indicators instead of rt tests!

**Comment by phatmann** [comment]
Glad to hear this! Thanks for following up.

**Comment by mjarvis** [comment]
Hi -- I recently encountered this issue as well and have come up with a (partial) solution.
I've copied the swift interfaces for `KIFUITestActor` and `KIFSystemTestActor` into protocols, and switched the described `XCTestCase` extension functions to return the protocols.
Anyone can include the three files in this gist into their test target to get autocomplete back for tester & the tester's functions.
https://gist.github.com/mjarvis/ff3c1ab8e5826eb1e7e8b773881dcd0f

**Comment by abbeyjackson** [comment]
@skyem I've been talking with Malcolm on Slack and he has come up with this new method that works when the fix you found doesn't. On my old project at Metova your fix only worked for a week and then not again, you might want to try getting the dev on it to try this.

**Comment by phatmann** [comment]
@mjarvis Do you want us to bring these changes into KIF via a PR?

**Comment by mjarvis** [comment]
@phatmann I'm not sure these changes would work directly in KIF, since the autocomplete problem indicates that Xcode can't find the headers to begin with. Perhaps having some swift in there would resolve that. I'll give it a try.

**Comment by skyem** [comment]
@mjarvis Your fix is working well for me. I did add the `tryFindingViewWithAccessibilityLabel` and `waitForTimeInterval` methods, but am liking the result overall. I'll add a pr.

**Comment by LordNali** [comment]
@mjarvis approach works for us as well, but we're struggling to include the `waitFor(accessibilityIdentifier)` headers as well:

```
(UIView *)waitForViewWithAccessibilityIdentifier:(NSString *)accessibilityIdentifier;
(UIView *)waitForTappableViewWithAccessibilityIdentifier:(NSString *)accessibilityIdentifier;
```
adding (e.g.) this two methods to the Protocol don't work:
```
func waitForView(withAccessibilityIdentifier accessibilityIdentifier: String!) -> UIView!
func waitForTappableView(withAccessibilityIdentifier: String!) -> UIView!
```

Xcode throws then:
```
/Testable Swift/__ObjC.KIFUITestActor:10:15: Method 'waitForView(withAccessibilityLabel:)' has different argument names from those required by protocol 'TestActor' ('waitForView(withAccessibilityIdentifier:)')
/Testable Swift/__ObjC.KIFUITestActor:57:15: Method 'waitForTappableView(withAccessibilityLabel:)' has different argument names from those required by protocol 'TestActor' ('waitForTappableView(withAccessibilityIdentifier:)')
```

What are we're missing here? (My Objective-C is literally non-existing).

**Comment by abbeyjackson** [comment]
@LordNali Your errors mention AccessibilityLabel and the methods you are trying to add say AccessibilityIdentifier

**Comment by LordNali** [comment]
Yeah, I noticed that to - but that's seems to be an error from Xcode - since the Accessibility**Label** Functions (in the Protocol) work perfectly. I guess what Xcode's trying to say is, that it can't distinguish between these two functions (label vs identifier) - both take a String as Argument and return a UIView. But since I'm using different Argument Names I hopped this could work, but it doesn't.

**Comment by abbeyjackson** [comment]
Maybe @mjarvis can shed some light

**Comment by mjarvis** [comment]
@LordNali The identifier tests don't seem to be publicly available as far as I can tell, but you can try this, if you've made them available in your project somehow: (note: untested)

```swift
@objc(waitForViewWithAccessibilityIdentifier:) func waitForView(withAccessibilityIdentifier accessibilityIdentifier: String!) -> UIView!
@objc(waitForTappableViewWithAccessibilityIdentifier:)func waitForTappableView(withAccessibilityIdentifier: String!) 
```

**Comment by LordNali** [comment]
@mjarvis Using you snippet I get the following error from Xcode:
`@objc can only be used with member of classes, @objc protocols, and concrete extensions of classes`

You said the accessibilityIdentifier aren't public? For testing purposes I moved the headers and sources from `KIFUITestActor-IdentifierTest.h/.m` to `KIFUITestActor.h/.m` - but even then, I can't use the accessibilityIdentifier Routines - what am I'm missing here?

`Value of type '(String, Int) -> TestActor' has no member 'waitForView'`

**Comment by LordNali** [comment]
@mjarvis Using you snippet I get the following error from Xcode:
`@objc can only be used with member of classes, @objc protocols, and concrete extensions of classes`

You said the accessibilityIdentifier aren't public? I added the IdentifierTests to KIF.h - now I can access them from my Swift Code. But the Tests themselves don't work (anymore) - see exception below.

Furthermore the waitFor(accessibilityLabel) Functions don't work either - and the View I'm looking for is there (with the supplied AccessibilityLabel **and** AccessibilityIdentifier).

It seems that KIF don't find any of my views, regardless if they're actually there or not.

```
2017-02-28 12:13:11.397 my_app[60842:1894375] -[KIFUITestActor waitForViewWithAccessibilityIdentifier:]: unrecognized selector sent to instance 0x60800046b400
/myTest.swift:111: error: -[myTest Test1] : failed: caught "NSInvalidArgumentException", "-[KIFUITestActor waitForViewWithAccessibilityIdentifier:]: unrecognized selector sent to instance 0x60800046b400"
(
	0   CoreFoundation                      0x000000010d4f5d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010cf5721e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d565f04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010d47b005 ___forwarding___ + 1013
	4   CoreFoundation                      0x000000010d47ab88 _CF_forwarding_prep_0 + 120
	5   viewer_test_trace                   0x00000001232fa6c1 _TFC17myTest17myTest14Test1T_T_ + 257
	6   viewer_test_trace                   0x00000001232fa732 _TToFC17myTest17myTest14Terst1fT_T_ + 34
	7   CoreFoundation                      0x000000010d47c44c __invoking___ + 140
	8   CoreFoundation                      0x000000010d47c2d1 -[NSInvocation invoke] + 289
	9   XCTest                              0x00000001228baf77 __24-[XCTestCase invokeTest]_block_invoke_2 + 481
	10  XCTest                              0x00000001228f37df -[XCTestContext performInScope:] + 190
	11  XCTest                              0x00000001228bad83 -[XCTestCase invokeTest] + 255
	12  XCTest                              0x00000001228bb59c -[XCTestCase performTest:] + 457
	13  XCTest                              0x00000001228b8664 -[XCTestSuite performTest:] + 491
	14  XCTest                              0x00000001228b8664 -[XCTestSuite performTest:] + 491
	15  XCTest                              0x00000001228b8664 -[XCTestSuite performTest:] + 491
	16  XCTest                              0x00000001228a4618 __25-[XCTestDriver _runSuite]_block_invoke + 51
	17  XCTest                              0x00000001228c5d2b -[XCTestObservationCenter _observeTestExecutionForBlock:] + 602
	18  XCTest                              0x00000001228a44b5 -[XCTestDriver _runSuite] + 436
	19  XCTest                              0x00000001228a5302 -[XCTestDriver _checkForTestManager] + 287
	20  XCTest                              0x00000001228f4d67 _XCTestMain + 628
	21  CoreFoundation                      0x000000010d49a6ac __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	22  CoreFoundation                      0x000000010d47f6f4 __CFRunLoopDoBlocks + 356
	23  CoreFoundation                      0x000000010d47ee65 __CFRunLoopRun + 901
	24  CoreFoundation                      0x000000010d47e884 CFRunLoopRunSpecific + 420
	25  GraphicsServices                    0x0000000111487a6f GSEventRunModal + 161
	26  UIKit                               0x0000000108624c68 UIApplicationMain + 159
	27  viewer_app                          0x000000010745d2af main + 111
	28  libdyld.dylib                       0x000000010ff0f68d start + 1
)
```

The following Function always return nil:

```
- (void)waitForAccessibilityElement:(UIAccessibilityElement **)element view:(out UIView **)view withLabel:(NSString *)label value:(NSString *)value traits:(UIAccessibilityTraits)traits tappable:(BOOL)mustBeTappable
{
    [self runBlock:^KIFTestStepResult(NSError **error) {
        return [UIAccessibilityElement accessibilityElement:element view:view withLabel:label value:value traits:traits tappable:mustBeTappable error:error] ? KIFTestStepResultSuccess : KIFTestStepResultWait;
    }];
}

```

**Comment by LordNali** [comment]
I made two PRs regarding this Issue #950  and #951.

**Comment by phatmann** [comment]
I just merged #950. I am waiting for more info about #951.

**Comment by JustinM1** [comment]
In case anyone still experiences issues with this what I do is go to manage schemes and mark the show checkbox for KIF. Then switch over to the KIF scheme and cmd + b. Then switch back to testing scheme and cmd + b again. Seems to do the trick for KIF, as well as Quick and Nimble.
